version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm
          command: npm install
      - setup_remote_docker:
          docker_layer_caching: false

      - run: |
          docker build -t rsenuatnu.azurecr.io/trust-new-art-client:latest -t rsenuatnu.azurecr.io/trust-new-server:$CIRCLE_SHA1 .
          docker login -u $DOCKER_USER -p $DOCKER_PASS rsenuatnu.azurecr.io
          docker push rsenuatnu.azurecr.io/trust-new-art-server:latest
          docker push rsenuatnu.azurecr.io/trust-new-art-server:$CIRCLE_SHA1

      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: atnu-context
